# Generated by Django 3.1.1 on 2020-09-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeApp', '0002_auto_20200929_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='catrgory',
            new_name='category',
        ),
    ]
