# Generated by Django 3.1.1 on 2020-10-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeApp', '0004_auto_20200930_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail/'),
        ),
    ]
