# Generated by Django 3.1.1 on 2020-12-10 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtubeApp', '0006_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofiles',
            name='dislikes',
            field=models.ManyToManyField(related_name='video_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videofiles',
            name='likes',
            field=models.ManyToManyField(related_name='video_loved', to=settings.AUTH_USER_MODEL),
        ),
    ]
