# Generated by Django 3.1.1 on 2021-02-11 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtubeApp', '0007_auto_20201210_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='subcribers',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
