# Generated by Django 3.1.1 on 2021-02-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeApp', '0009_videocomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
